// src/components/pages/article/content-body.svelte
<div
  class="redgoose-body redgoose-body--dark"
  aria-hidden="true"
  on:click={onClickBody}>
  {#if body}
    {@html body}
  {/if}
</div>

<script>
import { createEventDispatcher } from 'svelte'

const dispatch = createEventDispatcher()
export let body = undefined

function onClickBody(e)
{
  let _target = e.target
  switch (_target.tagName?.toLowerCase())
  {
    case 'img':
      dispatch('openLightbox', {
        src: _target.src,
        alt: _target.alt,
      })
      break
    case 'goose-dark-mode-image':
      dispatch('openLightbox', {
        src: _target.getAttribute('src-light'),
        srcDark: _target.getAttribute('src-dark'),
        alt: _target.getAttribute('alt'),
      })
      break
  }
}
</script>

<style src="./content-body.scss" lang="scss"></style>

// client/components/article/content-body.vue
<template>
<div
  ref="$content"
  v-html="props.content"
  class="redgoose-body redgoose-body--dark"/>
</template>

<script setup>
import { ref, onMounted } from 'vue'

const props = defineProps({
  content: String,
})
const emits = defineEmits([ 'click:image' ])
const $content = ref()

onMounted(() => {
  $content.value.querySelectorAll('img, goose-dark-mode-image').forEach(el => {
    el.addEventListener('click', onClickImage)
  })
})

function onClickImage(e)
{
  emits('click:image', {
    src: e.target.getAttribute('src') || e.target.getAttribute('src-light'),
    srcDark: e.target.getAttribute('src-dark'),
    alt: e.target.getAttribute('alt'),
  })
}
</script>

<style src="./content-body.scss" lang="scss"></style>
