// client/pages/nest/index.vue
<template>
<Loading v-if="state.loading"/>
<article v-else class="nest">
  <header v-if="state.nest?.name" class="nest-header">
    <h1>{{state.nest.name}}</h1>
  </header>
  <nav v-if="state.category.length > 0" class="nest-category">
    <Category
      :nest="route.params.code"
      :items="state.category"
      :active="route.params.category"/>
  </nav>
  <div class="body">
    <Loading v-if="state.articleLoading"/>
    <div v-else-if="state.article?.length > 0" class="index">
      <Items>
        <li v-for="o in state.article">
          <Item
            :srl="o.srl"
            :title="o.title"
            :image="o.image"
            :description="`${o.nest} / ${o.category}`"/>
        </li>
      </Items>
    </div>
    <Error
      v-else
      page-title="No Content"
      :error="new ServiceError('No Content', 204)"
      class="empty"/>
  </div>
  <div v-if="state.total > 0" class="nest-paginate">
    <Paginate
        :page="route.query.page"
        :total="state.total"
        :size="state.assets.size"
        :range="3"
        class="paginate--mobile"
        @update:page="onChangePage"/>
      <Paginate
        :page="route.query.page"
        :total="state.total"
        :size="state.assets.size"
        :range="10"
        class="paginate--desktop"
        @update:page="onChangePage"/>
  </div>
</article>
</template>

<script setup>
import { reactive, onMounted, watch } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { ofetch } from 'ofetch'
import ServiceError from '../../libs/error.js'
import { serialize } from '../../libs/strings.js'
import { scrollTo } from '../../libs/util.js'
import Error from '../../components/content/error.vue'
import Category from '../../components/content/category.vue'
import Items from '../../components/content/items.vue'
import Item from '../../components/content/item.vue'
import Loading from '../../components/etc/loading.vue'
import Paginate from '../../components/etc/paginate.vue'

const router = useRouter()
const route = useRoute()
const state = reactive({
  loading: true,
  articleLoading: false,
  total: 0,
  nest: {},
  article: [],
  category: [],
  assets: { size: 24 },
})

onMounted(_fetch)
watch(() => [ route.params, route.query.page ], (value, oldValue) => {
  const [ params, page ] = value
  const [ oldParams, oldPage ] = oldValue
  if (params.code !== oldParams.code)
  {
    _fetch().then()
  }
  else if (params.category !== oldParams.category)
  {
    _fetchArticle().then()
  }
  else if (page !== oldPage)
  {
    _fetchArticle().then()
  }
})

async function _fetch()
{
  try
  {
    scrollTo(0)
    state.loading = true
    let _url = `/api/nest/${route.params.code}/`
    if (route.params.category) _url += `${route.params.category}/`
    let _query = { nest: state.nest.srl }
    if (route.query.page > 1) _query.page = Number(route.query.page)
    const res = await ofetch(_url, { query: _query })
    if (!res) throw new ServiceError('No Content', 204)
    state.nest = res.nest
    state.category = res.category
    state.total = res.article.total
    state.article = res.article.index
    state.assets.size = res.assets.size
  }
  catch (_e)
  {
    if (_e instanceof ServiceError)
    {
      if (_e.code !== 204) throw _e
    }
    else
    {
      throw new ServiceError(_e?.message)
    }
  }
  finally
  {
    state.loading = false
  }
}

async function _fetchArticle()
{
  if (state.loading) return
  try
  {
    scrollTo(0)
    state.articleLoading = true
    let _query = { nest: state.nest.srl }
    if (route.params.category) _query.category = route.params.category
    if (route.query.page > 1) _query.page = Number(route.query.page)
    const res = await ofetch(`/api/article/`, { query: _query })
    if (!res) throw new ServiceError('No Content', 204)
    state.total = res.total
    state.article = res.index
  }
  catch (_e)
  {
    if (_e instanceof ServiceError)
    {
      if (_e.code === 204) state.article = []
      else throw _e
    }
    else
    {
      throw new ServiceError(_e?.message)
    }
  }
  finally
  {
    state.articleLoading = false
  }
}

function onChangePage(page)
{
  let _query = { ...route.query }
  _query.page = page > 1 ? page : NaN
  router.push(`./${serialize(_query, true)}`).then()
}
</script>

<style src="./index.scss" lang="scss" scoped></style>

// src/pages/nest.svelte
{#if loading}
  <Loading full={true} move={true}/>
{:else}
  <article class="nest">
    {#if nest?.title}
      <header class="nest__header">
        <h1>
          <span>{nest.title}</span>
        </h1>
      </header>
    {/if}
    {#if categories?.length > 0}
      <div class="nest__categories">
        <Categories
          items={_categories}
          active={route.params.category || ''}/>
      </div>
    {/if}
    <div class="nest__body">
      {#if articles?.length > 0}
        <div class="nest__items">
          <Items>
            {#each articles as o, key}
              <Item
                srl={o.srl}
                title={o.title}
                image={o.image}
                description={o.date}/>
            {/each}
          </Items>
        </div>
      {:else}
        <div class="nest__empty">
          <Error status={204} message="no articles"/>
        </div>
      {/if}
      {#if totalArticles > 0}
        <div class="nest__paginate">
          <Paginate
            page={route.query.page}
            total={totalArticles}
            size={size}
            url="./"
            query={router.location.query.get()}/>
        </div>
      {/if}
    </div>
  </article>
{/if}

<script>
import { router } from 'tinro'
import { ofetch } from 'ofetch'
import { error } from '../store'
import Error from '../components/error.svelte'
import Categories from '../components/pages/index/categories.svelte'
import Items from '../components/pages/index/items.svelte'
import Item from '../components/pages/index/item.svelte'
import Paginate from '../components/paginate.svelte'
import Loading from '../components/loading/loading-page.svelte'

export let route
let currentRoute
let size = Number(import.meta.env.VITE_INDEX_SIZE)
let nest = undefined
let categories = []
let totalArticles = 0
let articles = []
let loading = false

$: if (currentRoute?.params?.nest !== route.params?.nest) updateNest()
$: if (currentRoute?.params?.category !== route.params.category) updateCategory()
$: if (currentRoute?.query.page !== route.query.page) updatePage()

$: _categories = categories.map(o => {
  return {
    srl: o.srl ? String(o.srl) : '',
    label: o.name,
    count: o.count_article,
    link: o.srl ? `/nest/${currentRoute.params?.nest}/${o.srl}/` : `/nest/${currentRoute.params?.nest}/`,
  }
})

async function updateNest()
{
  try
  {
    currentRoute = route
    loading = true
    let query = {}
    if (route.params.category)
    {
      query.categorySrl = route.params.category || ''
    }
    if (Number(route.query?.page) > 1)
    {
      query.page = Number(route.query?.page)
    }
    let res = await ofetch(`/api/nests/${route.params?.nest}/`, {
      responseType: 'json',
      query,
    })
    nest = res.nest || undefined
    categories = res.categories || []
    totalArticles = res.articles?.total || 0
    articles = res.articles?.items || []
    loading = false
  }
  catch (e)
  {
    const status = e.response?._data?.status || 500
    const message = e.response?._data?.message || 'Unknown error'
    error.update(() => ({ status, message }))
    loading = false
  }
}

async function updateCategory()
{
  try
  {
    currentRoute = route
    loading = true
    let query = {}
    if (route.params.category)
    {
      query.categorySrl = route.params.category || ''
    }
    let res = await ofetch(`/api/nests/${nest.srl}/articles/`, {
      responseType: 'json',
      query,
    })
    totalArticles = res?.total || 0
    articles = res?.items || []
    loading = false
  }
  catch (e)
  {
    const status = e.response?._data?.status || 500
    const message = e.response?._data?.message || 'Unknown error'
    error.update(() => ({ status, message }))
    loading = false
  }
}

async function updatePage()
{
  try
  {
    currentRoute = route
    loading = true
    let query = {}
    if (route.params.category)
    {
      query.categorySrl = route.params.category || ''
    }
    if (Number(route.query?.page) > 1)
    {
      query.page = Number(route.query?.page)
    }
    let res = await ofetch(`/api/nests/${nest.srl}/articles/`, {
      responseType: 'json',
      query,
    })
    totalArticles = res?.total || 0
    articles = res?.items || []
    loading = false
  }
  catch (e)
  {
    const status = e.response?._data?.status || 500
    const message = e.response?._data?.message || 'Unknown error'
    error.update(() => ({ status, message }))
    loading = false
  }
}
</script>

<style src="./nest.scss" lang="scss"></style>
