// client/pages/page/about.vue
<template>
<article class="about">
  <div class="wrap">
    <header class="header">
      <p>Introduce</p>
      <h1>{{data.title}}</h1>
    </header>
    <figure class="profile">
      <img
        :srcset="[ `${data.coverImage.src[1]} 2x`, `${data.coverImage.src[0]} 1x` ].join(', ')"
        :src="data.coverImage.src[0]"
        :alt="data.coverImage.alt"
        width="256"
        height="256"/>
    </figure>
    <div class="description">
      <p v-html="data.description"/>
    </div>
    <div class="meta">
      <section v-for="o in data.information">
        <h1>{{o.title}}</h1>
        <dl>
          <template v-for="oo in o.items">
            <dt>{{oo.label}}</dt>
            <dd v-html="oo.body"/>
          </template>
        </dl>
      </section>
    </div>
  </div>
</article>
</template>

<script setup>
import data from '../../../server/resource/about.json'
</script>

<style src="./about.scss" lang="scss" scoped></style>

// server/endpoints/service/page/About.jsx
import { isDev, onRequest, onResponse, printMessage } from '../../../libs/server.js'
import { setResponse, checkingBot, renderIndex } from '../_libs.js'
import Layout from '../components/Layout.jsx'
import ErrorScreen from '../components/ErrorScreen.jsx'

const dev = isDev()

async function PageAbout(req, _ctx)
{
  let response

  // trigger request event
  onRequest(req, _ctx)

  try
  {
    if (checkingBot(req))
    {
      const file = Bun.file('./server/resource/about.json')
      const about = await file.json()
      response = setResponse((
        <Layout>
          <article>
            <header>
              <p>Introduce</p>
              <h1>{about.title}</h1>
              <figure>
                <img src={about.coverImage.src[1]} alt={about.coverImage.alt}/>
              </figure>
              <p>{about.description}</p>
            </header>
            {about.information.map((content) => (
              <section>
                <h1>{content.title}</h1>
                <dl>
                  {content.items.map(item => (
                    <>
                      <dt>{item.label}</dt>
                      <dd>{item.body}</dd>
                    </>
                  ))}
                </dl>
              </section>
            ))}
          </article>
        </Layout>
      ))
    }
    else
    {
      response = await renderIndex(req)
    }
  }
  catch (_e)
  {
    if (dev) printMessage('error', `[${_e.status || 500}] ${_e.message}`)
    response = setResponse((
      <ErrorScreen message="Failed get data."/>
    ), _e.status || 500)
  }

  // trigger response event
  onResponse(req, response, _ctx)

  return response
}

export default PageAbout
