// src/pages/article.svelte
<article class="article">
  {#if loading}
    <Loading full={true} move={true}/>
  {:else if empty}
    <div class="article__empty">
      <Error status={204} message="no article"/>
    </div>
  {:else}
    <div class="article__wrap">
      <header class="article__header">
        {#if headDescription?.length > 0}
          <p>
            {#each headDescription as label}
              <span>{label}</span>
            {/each}
            <em>{order}</em>
          </p>
        {/if}
        <h1>{title === '.' ? 'Untitled work' : title}</h1>
      </header>
      <div class="article__body">
        <ContentBody
          body={_contentBody}
          on:openLightbox={onOpenLightbox}/>
      </div>
      <nav class="article__star">
        <StarButton
          count={starButton.count}
          disabled={starButton.disabled}
          on:click={onClickStar}/>
      </nav>
    </div>
  {/if}
</article>
{#if lightbox?.src}
  <LightBox
    {...lightbox}
    on:close={onCloseLightbox}/>
{/if}

<script>
import { onMount } from 'svelte'
import { ofetch } from 'ofetch'
import { error } from '../store'
import { hashScroll } from '../libs/util'
import Loading from '../components/loading/loading-page.svelte'
import Error from '../components/error.svelte'
import StarButton from '../components/pages/article/star-button.svelte'
import ContentBody from '../components/pages/article/content-body.svelte'
import LightBox from '../components/pages/article/lightbox.svelte'

export let route
let loading = true
let srl
let title
let headDescription
let order
let contentBody
let starButton = {
  disabled: false,
  count: 0,
}
let empty = false
let lightbox = {}

$: _contentBody = contentBody

async function fetchData()
{
  try
  {
    loading = true
    let res = await ofetch(`/api/article/${route.params.article}/`, {
      responseType: 'json',
    })
    srl = res.srl
    title = res.title
    headDescription = [ res.nestName, res.categoryName ]
    order = res.order
    contentBody = res.content
    starButton.disabled = !res.enableStarButton
    starButton.count = res.star
    loading = false
    // move scroll
    hashScroll(location.hash)
  }
  catch (e)
  {
    const status = e.response?._data?.status || 500
    const message = e.response?._data?.message || 'Unknown error'
    if (status === 404)
    {
      empty = true
    }
    else
    {
      error.update(() => ({ status, message }))
    }
    loading = false
  }
}

async function onClickStar()
{
  try
  {
    let res = await ofetch(`/api/article/${route.params.article}/star/`, {
      method: 'post',
      responseType: 'json',
    })
    starButton.disabled = true
    starButton.count = Number(res.star)
    if (!res.success) throw new Error(res.message)
  }
  catch (e)
  {
    alert('Failed update star')
  }
}

function onOpenLightbox({ detail: { src, srcDark, alt } })
{
  lightbox.src = src
  lightbox.srcDark = srcDark
  lightbox.alt = alt
}

function onCloseLightbox()
{
  lightbox.src = undefined
  lightbox.srcDark = undefined
  lightbox.alt = undefined
}

onMount(() => fetchData().then())
</script>

<style src="./article.scss" lang="scss"></style>

// client/pages/article/index.vue
<template>
<article class="article">
  <Loading v-if="state.loading"/>
  <div v-else-if="state.srl" class="wrap">
    <header class="article-header">
      <p>
        <span v-for="o in state.headDescription">{{o}}</span>
        <em>{{_date}}</em>
      </p>
      <h1>{{state.title === '.' ? 'Untitled Work' : state.title}}</h1>
    </header>
    <div class="article-body">
      <ContentBody
        :content="state.content"
        @click:image="onClickImage"/>
    </div>
    <nav class="article-star">
      <StarButton
        :count="state.star.count"
        :disabled="state.star.disabled"
        @click:button="onClickStar"/>
    </nav>
  </div>
  <Error
    v-else
    page-title="No Content"
    :error="new ServiceError('No Content', 204)"
    class="article-empty"/>
  <teleport to="#modal">
    <Lightbox
      :src="state.lightbox?.src"
      :src-dark="state.lightbox?.srcDark"
      :alt="state.lightbox?.alt"
      @close="onCloseLightbox"/>
  </teleport>
</article>
</template>

<script setup>
import { reactive, computed, onMounted, nextTick } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { ofetch } from 'ofetch'
import ServiceError from '../../libs/error.js'
import { hashScroll } from '../../libs/util.js'
import { dateFormat } from '../../libs/strings.js'
import Error from '../error/index.vue'
import Loading from '../../components/etc/loading.vue'
import ContentBody from '../../components/article/content-body.vue'
import StarButton from '../../components/article/star-button.vue'
import Lightbox from '../../components/article/lightbox.vue'

const router = useRouter()
const route = useRoute()
const state = reactive({
  loading: true,
  srl: NaN,
  title: '',
  headDescription: [],
  regdate: '',
  content: '',
  star: {
    disabled: false,
    count: 0,
  },
  lightbox: null, // { src, srcDark, alt }
})

const _date = computed(() => {
  if (!state.regdate) return null
  return dateFormat(new Date(state.regdate), '{yyyy}-{MM}-{dd}')
})

onMounted(async () => {
  try
  {
    state.loading = true
    const res = await ofetch(`/api/article/${route.params.srl}/`)
    if (!res) throw new ServiceError('No Content', 204)
    state.srl = res.srl
    state.title = res.title
    state.headDescription = [ res.nestName, res.categoryName ]
    state.regdate = res.regdate
    state.content = res.content
    state.star.count = res.star
    state.star.disabled = res.usedUpStar
    // scroll to hash content
    if (location.hash)
    {
      await nextTick()
      hashScroll(location.hash)
    }
  }
  catch (_e)
  {
    if (_e instanceof ServiceError)
    {
      if (_e.code !== 204) throw _e
    }
    else
    {
      throw new ServiceError(_e?.message)
    }
  }
  finally
  {
    state.loading = false
  }
})

function onClickImage({ src, srcDark, alt })
{
  state.lightbox = { src, srcDark, alt }
}

function onCloseLightbox()
{
  state.lightbox = null
}

async function onClickStar()
{
  try
  {
    const res = await ofetch(`/api/article/${route.params.srl}/star/`, {
      method: 'post',
    })
    state.star.disabled = true
    state.star.count = res.count
  }
  catch (_e)
  {
    alert('Failed update star.')
  }
}
</script>

<style src="./index.scss" lang="scss" scoped></style>
