// client/pages/page/about.vue
<template>
<article class="about">
  <div class="wrap">
    <header class="header">
      <p>Introduce</p>
      <h1>{{data.title}}</h1>
    </header>
    <figure class="profile">
      <img
        :srcset="[ `${data.coverImage.src[1]} 2x`, `${data.coverImage.src[0]} 1x` ].join(', ')"
        :src="data.coverImage.src[0]"
        :alt="data.coverImage.alt"
        width="256"
        height="256"/>
    </figure>
    <div class="description">
      <p v-html="data.description"/>
    </div>
    <div class="meta">
      <section v-for="o in data.information">
        <h1>{{o.title}}</h1>
        <dl>
          <template v-for="oo in o.items">
            <dt>{{oo.label}}</dt>
            <dd v-html="oo.body"/>
          </template>
        </dl>
      </section>
    </div>
  </div>
</article>
</template>

<script setup>
import data from '../../../server/resource/about.json'
</script>

<style src="./about.scss" lang="scss" scoped></style>

// src/pages/page/about.svelte
<article class="about">
  <div class="about__wrap">
    <header class="about__header">
      <p>Introduce</p>
      <h1>{content.title}</h1>
    </header>
    <figure class="about__profile">
      <img
        srcset={`${content.coverImage.src[1]} 2x, ${content.coverImage.src[0]} 1x`}
        src={content.coverImage.src[0]}
        alt={content.coverImage.alt}/>
    </figure>
    <div class="about__description">
      <p>
        {@html content.description}
      </p>
    </div>
    <div class="about__metas">
      <div>
        {#each content.information as o,k}
          <section>
            <h1>{o.title}</h1>
            <dl>
              {#each o.items as oo}
                <dt>{oo.label}</dt>
                <dd>{@html oo.body}</dd>
              {/each}
            </dl>
          </section>
        {/each}
      </div>
    </div>
  </div>
</article>

<script>
import content from '../../../server/resource/about.json'
export let route = undefined
</script>

<style src="./about.scss" lang="scss"></style>
